name: Publish Artifacts
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install GPG
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          brew install gpg
          echo "$SIGNING_KEY" | gpg --dearmor > ${HOME}/secret_key.gpg

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Add gradle properties
        env:
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo "mavenCentralUsername=${MAVEN_CENTRAL_USERNAME}" >> data-class-mapper/gradle.properties
          echo "mavenCentralPassword=${MAVEN_CENTRAL_PASSWORD}" >> data-class-mapper/gradle.properties
          echo "signing.keyId=${SIGNING_KEY_ID}" >> data-class-mapper/gradle.properties
          echo "signing.password=${SIGNING_KEY_PASSWORD}" >> data-class-mapper/gradle.properties
          echo "signing.secretKeyRingFile=${HOME}/secret_key.gpg" >> data-class-mapper/gradle.properties

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Publish to Maven Central
        run: |
          ./gradlew :data-class-mapper:publishAndReleaseToMavenCentral --no-configuration-cache
